"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:07:13.465464
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_dependencies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_service', sa.String(length=64), nullable=False),
    sa.Column('target_service', sa.String(length=64), nullable=False),
    sa.Column('dependency_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_service', 'target_service', 'dependency_type', name='uq_dependency_edge')
    )
    op.create_index(op.f('ix_service_dependencies_source_service'), 'service_dependencies', ['source_service'], unique=False)
    op.create_index(op.f('ix_service_dependencies_status'), 'service_dependencies', ['status'], unique=False)
    op.create_index(op.f('ix_service_dependencies_target_service'), 'service_dependencies', ['target_service'], unique=False)
    op.create_table('service_health_checks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_health_checks_service_id'), 'service_health_checks', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_health_checks_status'), 'service_health_checks', ['status'], unique=False)
    op.create_table('sla_compliance',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('availability_pct', sa.Float(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'period', name='uq_sla_service_period')
    )
    op.create_index(op.f('ix_sla_compliance_period'), 'sla_compliance', ['period'], unique=False)
    op.create_index(op.f('ix_sla_compliance_service_id'), 'sla_compliance', ['service_id'], unique=False)
    op.create_index(op.f('ix_sla_compliance_status'), 'sla_compliance', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_compliance_status'), table_name='sla_compliance')
    op.drop_index(op.f('ix_sla_compliance_service_id'), table_name='sla_compliance')
    op.drop_index(op.f('ix_sla_compliance_period'), table_name='sla_compliance')
    op.drop_table('sla_compliance')
    op.drop_index(op.f('ix_service_health_checks_status'), table_name='service_health_checks')
    op.drop_index(op.f('ix_service_health_checks_service_id'), table_name='service_health_checks')
    op.drop_table('service_health_checks')
    op.drop_index(op.f('ix_service_dependencies_target_service'), table_name='service_dependencies')
    op.drop_index(op.f('ix_service_dependencies_status'), table_name='service_dependencies')
    op.drop_index(op.f('ix_service_dependencies_source_service'), table_name='service_dependencies')
    op.drop_table('service_dependencies')
    # ### end Alembic commands ###
