apiVersion: v1
kind: Service
metadata:
  name: {{ include "sm-fusion-platform.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector: {app.kubernetes.io/name: sm-fusion-platform}
  ports: [{name: http, port: {{ .Values.service.port }}, targetPort: http}]
