# ServiceAccount: sm-fusion-platform
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sm-fusion-platform.serviceAccountName" . }}
  labels:
    {{- include "sm-fusion-platform.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
